### ISSUE TITLE
The file is not saved

### ISSUE THREAD

**Issue by Goksel12211** [mydraft-cc/server-node#2]
The web server is ok, but when I click the "Save Diagram" button, a pop-up error message appears, stating "Failed to save diagram." Can you please help me understand what I might be doing incorrectly?
The command I tried :
`docker run -p 4000:4000 mydraftcc-nodejs-server` 
Web server is up but when i click Save Diagram button , i got an pop up error with Failed to save diagram. What am i doing wrong  ?

**Comment by SebastianStehle** [comment]
Is there no log on the server?

**Comment by Goksel12211** [comment]
when i click save diagram , web server throw a error in json : {"code":"EACCCES" , "errno":"-13", "message": "Error EACCES permission denied ,open  ''/data/123123....."........

**Comment by SebastianStehle** [comment]
There is probably a permission missing to access the file. You might need a volume mapping if you use docker.

**Comment by Goksel12211** [comment]
Thank you for your idea.
I simply **removed** the line :
`USER 1000:1000` in Dockerfile
 and it worked.
